const Database = require('better-sqlite3');
const path = require('path');

const dbPath = path.join(__dirname, 'local.db');
const db = new Database(dbPath);

// HSK 1-4 Character Data (300+ characters)
const characters = [
  // ─── HSK 1 (Core 80) ───
  { char: "我", pinyin: "wǒ", meaning: "I, me", strokes: 7, hsk: 1 },
  { char: "你", pinyin: "nǐ", meaning: "you", strokes: 7, hsk: 1 },
  { char: "他", pinyin: "tā", meaning: "he, him", strokes: 5, hsk: 1 },
  { char: "她", pinyin: "tā", meaning: "she, her", strokes: 6, hsk: 1 },
  { char: "们", pinyin: "men", meaning: "plural marker", strokes: 5, hsk: 1 },
  { char: "的", pinyin: "de", meaning: "possessive particle", strokes: 8, hsk: 1 },
  { char: "了", pinyin: "le", meaning: "completion particle", strokes: 2, hsk: 1 },
  { char: "在", pinyin: "zài", meaning: "at, in, on", strokes: 6, hsk: 1 },
  { char: "是", pinyin: "shì", meaning: "to be", strokes: 9, hsk: 1 },
  { char: "有", pinyin: "yǒu", meaning: "to have, exist", strokes: 6, hsk: 1 },
  { char: "不", pinyin: "bù", meaning: "not, no", strokes: 4, hsk: 1 },
  { char: "人", pinyin: "rén", meaning: "person, people", strokes: 2, hsk: 1 },
  { char: "大", pinyin: "dà", meaning: "big, large", strokes: 3, hsk: 1 },
  { char: "小", pinyin: "xiǎo", meaning: "small, little", strokes: 3, hsk: 1 },
  { char: "中", pinyin: "zhōng", meaning: "middle, center", strokes: 4, hsk: 1 },
  { char: "上", pinyin: "shàng", meaning: "up, above", strokes: 3, hsk: 1 },
  { char: "下", pinyin: "xià", meaning: "down, below", strokes: 3, hsk: 1 },
  { char: "好", pinyin: "hǎo", meaning: "good, well", strokes: 6, hsk: 1 },
  { char: "多", pinyin: "duō", meaning: "many, much", strokes: 6, hsk: 1 },
  { char: "少", pinyin: "shǎo", meaning: "few, little", strokes: 4, hsk: 1 },
  { char: "天", pinyin: "tiān", meaning: "sky, day", strokes: 4, hsk: 1 },
  { char: "年", pinyin: "nián", meaning: "year", strokes: 6, hsk: 1 },
  { char: "月", pinyin: "yuè", meaning: "month, moon", strokes: 4, hsk: 1 },
  { char: "日", pinyin: "rì", meaning: "day, sun", strokes: 4, hsk: 1 },
  { char: "时", pinyin: "shí", meaning: "time, hour", strokes: 7, hsk: 1 },
  { char: "分", pinyin: "fēn", meaning: "minute, divide", strokes: 4, hsk: 1 },
  { char: "今", pinyin: "jīn", meaning: "today, now", strokes: 4, hsk: 1 },
  { char: "明", pinyin: "míng", meaning: "bright, tomorrow", strokes: 8, hsk: 1 },
  { char: "昨", pinyin: "zuó", meaning: "yesterday", strokes: 9, hsk: 1 },
  { char: "前", pinyin: "qián", meaning: "front, before", strokes: 9, hsk: 1 },
  { char: "后", pinyin: "hòu", meaning: "back, after", strokes: 6, hsk: 1 },
  { char: "里", pinyin: "lǐ", meaning: "inside, mile", strokes: 7, hsk: 1 },
  { char: "家", pinyin: "jiā", meaning: "home, family", strokes: 10, hsk: 1 },
  { char: "学", pinyin: "xué", meaning: "to study, learn", strokes: 8, hsk: 1 },
  { char: "校", pinyin: "xiào", meaning: "school", strokes: 10, hsk: 1 },
  { char: "生", pinyin: "shēng", meaning: "born, student", strokes: 5, hsk: 1 },
  { char: "老", pinyin: "lǎo", meaning: "old, teacher", strokes: 6, hsk: 1 },
  { char: "师", pinyin: "shī", meaning: "teacher, master", strokes: 6, hsk: 1 },
  { char: "书", pinyin: "shū", meaning: "book", strokes: 4, hsk: 1 },
  { char: "写", pinyin: "xiě", meaning: "to write", strokes: 5, hsk: 1 },
  { char: "读", pinyin: "dú", meaning: "to read", strokes: 10, hsk: 1 },
  { char: "说", pinyin: "shuō", meaning: "to speak, say", strokes: 9, hsk: 1 },
  { char: "听", pinyin: "tīng", meaning: "to listen", strokes: 7, hsk: 1 },
  { char: "看", pinyin: "kàn", meaning: "to look, watch", strokes: 9, hsk: 1 },
  { char: "吃", pinyin: "chī", meaning: "to eat", strokes: 6, hsk: 1 },
  { char: "喝", pinyin: "hē", meaning: "to drink", strokes: 12, hsk: 1 },
  { char: "水", pinyin: "shuǐ", meaning: "water", strokes: 4, hsk: 1 },
  { char: "茶", pinyin: "chá", meaning: "tea", strokes: 9, hsk: 1 },
  { char: "饭", pinyin: "fàn", meaning: "meal, rice", strokes: 7, hsk: 1 },
  { char: "菜", pinyin: "cài", meaning: "vegetable, dish", strokes: 11, hsk: 1 },
  { char: "米", pinyin: "mǐ", meaning: "rice, meter", strokes: 6, hsk: 1 },
  { char: "买", pinyin: "mǎi", meaning: "to buy", strokes: 6, hsk: 1 },
  { char: "钱", pinyin: "qián", meaning: "money", strokes: 10, hsk: 1 },
  { char: "东", pinyin: "dōng", meaning: "east", strokes: 5, hsk: 1 },
  { char: "西", pinyin: "xī", meaning: "west", strokes: 6, hsk: 1 },
  { char: "北", pinyin: "běi", meaning: "north", strokes: 5, hsk: 1 },
  { char: "南", pinyin: "nán", meaning: "south", strokes: 9, hsk: 1 },
  { char: "开", pinyin: "kāi", meaning: "to open, start", strokes: 4, hsk: 1 },
  { char: "关", pinyin: "guān", meaning: "to close, concern", strokes: 6, hsk: 1 },
  { char: "来", pinyin: "lái", meaning: "to come", strokes: 7, hsk: 1 },
  { char: "去", pinyin: "qù", meaning: "to go", strokes: 5, hsk: 1 },
  { char: "回", pinyin: "huí", meaning: "to return", strokes: 6, hsk: 1 },
  { char: "走", pinyin: "zǒu", meaning: "to walk, go", strokes: 7, hsk: 1 },
  { char: "坐", pinyin: "zuò", meaning: "to sit", strokes: 7, hsk: 1 },
  { char: "住", pinyin: "zhù", meaning: "to live, reside", strokes: 7, hsk: 1 },
  { char: "做", pinyin: "zuò", meaning: "to do, make", strokes: 11, hsk: 1 },
  { char: "想", pinyin: "xiǎng", meaning: "to think, want", strokes: 13, hsk: 1 },
  { char: "会", pinyin: "huì", meaning: "can, meeting", strokes: 6, hsk: 1 },
  { char: "能", pinyin: "néng", meaning: "can, able to", strokes: 10, hsk: 1 },
  { char: "爱", pinyin: "ài", meaning: "love", strokes: 10, hsk: 1 },
  { char: "车", pinyin: "chē", meaning: "car, vehicle", strokes: 4, hsk: 1 },
  { char: "电", pinyin: "diàn", meaning: "electricity", strokes: 5, hsk: 1 },
  { char: "话", pinyin: "huà", meaning: "speech, word", strokes: 8, hsk: 1 },
  { char: "手", pinyin: "shǒu", meaning: "hand", strokes: 4, hsk: 1 },
  { char: "机", pinyin: "jī", meaning: "machine, phone", strokes: 6, hsk: 1 },
  { char: "名", pinyin: "míng", meaning: "name", strokes: 6, hsk: 1 },
  { char: "字", pinyin: "zì", meaning: "character, word", strokes: 6, hsk: 1 },
  { char: "号", pinyin: "hào", meaning: "number", strokes: 5, hsk: 1 },
  { char: "几", pinyin: "jǐ", meaning: "how many", strokes: 2, hsk: 1 },
  { char: "岁", pinyin: "suì", meaning: "years old", strokes: 6, hsk: 1 },

  // ─── HSK 2 (80 characters) ───
  { char: "长", pinyin: "cháng", meaning: "long, grow", strokes: 4, hsk: 2 },
  { char: "高", pinyin: "gāo", meaning: "tall, high", strokes: 10, hsk: 2 },
  { char: "快", pinyin: "kuài", meaning: "fast, quick", strokes: 7, hsk: 2 },
  { char: "慢", pinyin: "màn", meaning: "slow", strokes: 14, hsk: 2 },
  { char: "新", pinyin: "xīn", meaning: "new", strokes: 13, hsk: 2 },
  { char: "旧", pinyin: "jiù", meaning: "old, used", strokes: 5, hsk: 2 },
  { char: "近", pinyin: "jìn", meaning: "near, close", strokes: 7, hsk: 2 },
  { char: "远", pinyin: "yuǎn", meaning: "far, distant", strokes: 7, hsk: 2 },
  { char: "早", pinyin: "zǎo", meaning: "early, morning", strokes: 6, hsk: 2 },
  { char: "晚", pinyin: "wǎn", meaning: "late, evening", strokes: 11, hsk: 2 },
  { char: "白", pinyin: "bái", meaning: "white, blank", strokes: 5, hsk: 2 },
  { char: "黑", pinyin: "hēi", meaning: "black, dark", strokes: 12, hsk: 2 },
  { char: "红", pinyin: "hóng", meaning: "red", strokes: 6, hsk: 2 },
  { char: "让", pinyin: "ràng", meaning: "to let, allow", strokes: 5, hsk: 2 },
  { char: "给", pinyin: "gěi", meaning: "to give", strokes: 9, hsk: 2 },
  { char: "找", pinyin: "zhǎo", meaning: "to look for", strokes: 7, hsk: 2 },
  { char: "到", pinyin: "dào", meaning: "to arrive, reach", strokes: 8, hsk: 2 },
  { char: "问", pinyin: "wèn", meaning: "to ask", strokes: 6, hsk: 2 },
  { char: "答", pinyin: "dá", meaning: "to answer", strokes: 12, hsk: 2 },
  { char: "起", pinyin: "qǐ", meaning: "to rise, get up", strokes: 10, hsk: 2 },
  { char: "笑", pinyin: "xiào", meaning: "to laugh, smile", strokes: 10, hsk: 2 },
  { char: "哭", pinyin: "kū", meaning: "to cry", strokes: 10, hsk: 2 },
  { char: "跑", pinyin: "pǎo", meaning: "to run", strokes: 12, hsk: 2 },
  { char: "游", pinyin: "yóu", meaning: "to swim, travel", strokes: 12, hsk: 2 },
  { char: "玩", pinyin: "wán", meaning: "to play", strokes: 8, hsk: 2 },
  { char: "唱", pinyin: "chàng", meaning: "to sing", strokes: 11, hsk: 2 },
  { char: "跳", pinyin: "tiào", meaning: "to jump, dance", strokes: 13, hsk: 2 },
  { char: "穿", pinyin: "chuān", meaning: "to wear", strokes: 9, hsk: 2 },
  { char: "洗", pinyin: "xǐ", meaning: "to wash", strokes: 9, hsk: 2 },
  { char: "送", pinyin: "sòng", meaning: "to send, deliver", strokes: 9, hsk: 2 },
  { char: "帮", pinyin: "bāng", meaning: "to help", strokes: 9, hsk: 2 },
  { char: "等", pinyin: "děng", meaning: "to wait", strokes: 12, hsk: 2 },
  { char: "完", pinyin: "wán", meaning: "to finish", strokes: 7, hsk: 2 },
  { char: "错", pinyin: "cuò", meaning: "wrong, mistake", strokes: 13, hsk: 2 },
  { char: "对", pinyin: "duì", meaning: "correct, right", strokes: 5, hsk: 2 },
  { char: "左", pinyin: "zuǒ", meaning: "left", strokes: 5, hsk: 2 },
  { char: "右", pinyin: "yòu", meaning: "right", strokes: 5, hsk: 2 },
  { char: "外", pinyin: "wài", meaning: "outside", strokes: 5, hsk: 2 },
  { char: "男", pinyin: "nán", meaning: "male, man", strokes: 7, hsk: 2 },
  { char: "女", pinyin: "nǚ", meaning: "female, woman", strokes: 3, hsk: 2 },
  { char: "孩", pinyin: "hái", meaning: "child", strokes: 9, hsk: 2 },
  { char: "子", pinyin: "zǐ", meaning: "child, son", strokes: 3, hsk: 2 },
  { char: "妈", pinyin: "mā", meaning: "mother", strokes: 6, hsk: 2 },
  { char: "爸", pinyin: "bà", meaning: "father", strokes: 8, hsk: 2 },
  { char: "哥", pinyin: "gē", meaning: "older brother", strokes: 10, hsk: 2 },
  { char: "姐", pinyin: "jiě", meaning: "older sister", strokes: 8, hsk: 2 },
  { char: "弟", pinyin: "dì", meaning: "younger brother", strokes: 7, hsk: 2 },
  { char: "妹", pinyin: "mèi", meaning: "younger sister", strokes: 8, hsk: 2 },
  { char: "身", pinyin: "shēn", meaning: "body", strokes: 7, hsk: 2 },
  { char: "体", pinyin: "tǐ", meaning: "body, form", strokes: 7, hsk: 2 },
  { char: "头", pinyin: "tóu", meaning: "head", strokes: 5, hsk: 2 },
  { char: "眼", pinyin: "yǎn", meaning: "eye", strokes: 11, hsk: 2 },
  { char: "耳", pinyin: "ěr", meaning: "ear", strokes: 6, hsk: 2 },
  { char: "口", pinyin: "kǒu", meaning: "mouth", strokes: 3, hsk: 2 },
  { char: "心", pinyin: "xīn", meaning: "heart, mind", strokes: 4, hsk: 2 },
  { char: "鱼", pinyin: "yú", meaning: "fish", strokes: 8, hsk: 2 },
  { char: "鸡", pinyin: "jī", meaning: "chicken", strokes: 7, hsk: 2 },
  { char: "猫", pinyin: "māo", meaning: "cat", strokes: 11, hsk: 2 },
  { char: "狗", pinyin: "gǒu", meaning: "dog", strokes: 8, hsk: 2 },
  { char: "花", pinyin: "huā", meaning: "flower", strokes: 7, hsk: 2 },
  { char: "树", pinyin: "shù", meaning: "tree", strokes: 9, hsk: 2 },
  { char: "山", pinyin: "shān", meaning: "mountain", strokes: 3, hsk: 2 },
  { char: "河", pinyin: "hé", meaning: "river", strokes: 8, hsk: 2 },
  { char: "路", pinyin: "lù", meaning: "road, path", strokes: 13, hsk: 2 },
  { char: "门", pinyin: "mén", meaning: "door, gate", strokes: 3, hsk: 2 },
  { char: "窗", pinyin: "chuāng", meaning: "window", strokes: 12, hsk: 2 },
  { char: "床", pinyin: "chuáng", meaning: "bed", strokes: 7, hsk: 2 },
  { char: "桌", pinyin: "zhuō", meaning: "table, desk", strokes: 10, hsk: 2 },
  { char: "椅", pinyin: "yǐ", meaning: "chair", strokes: 12, hsk: 2 },

  // ─── HSK 3 (80 characters) ───
  { char: "决", pinyin: "jué", meaning: "to decide", strokes: 6, hsk: 3 },
  { char: "定", pinyin: "dìng", meaning: "to decide, fixed", strokes: 8, hsk: 3 },
  { char: "变", pinyin: "biàn", meaning: "to change", strokes: 8, hsk: 3 },
  { char: "化", pinyin: "huà", meaning: "to change, transform", strokes: 4, hsk: 3 },
  { char: "发", pinyin: "fā", meaning: "to send, develop", strokes: 5, hsk: 3 },
  { char: "现", pinyin: "xiàn", meaning: "present, appear", strokes: 8, hsk: 3 },
  { char: "感", pinyin: "gǎn", meaning: "to feel, sense", strokes: 13, hsk: 3 },
  { char: "觉", pinyin: "jué", meaning: "to feel, sense", strokes: 9, hsk: 3 },
  { char: "信", pinyin: "xìn", meaning: "letter, believe", strokes: 9, hsk: 3 },
  { char: "关", pinyin: "guān", meaning: "close, concern", strokes: 6, hsk: 3 },
  { char: "系", pinyin: "xì", meaning: "system, relate", strokes: 7, hsk: 3 },
  { char: "注", pinyin: "zhù", meaning: "to pour, focus", strokes: 8, hsk: 3 },
  { char: "意", pinyin: "yì", meaning: "meaning, intention", strokes: 13, hsk: 3 },
  { char: "需", pinyin: "xū", meaning: "to need", strokes: 14, hsk: 3 },
  { char: "要", pinyin: "yào", meaning: "want, need, important", strokes: 9, hsk: 3 },
  { char: "应", pinyin: "yīng", meaning: "should, respond", strokes: 7, hsk: 3 },
  { char: "该", pinyin: "gāi", meaning: "should, ought to", strokes: 8, hsk: 3 },
  { char: "必", pinyin: "bì", meaning: "must, certainly", strokes: 5, hsk: 3 },
  { char: "须", pinyin: "xū", meaning: "must, beard", strokes: 9, hsk: 3 },
  { char: "经", pinyin: "jīng", meaning: "pass through, already", strokes: 8, hsk: 3 },
  { char: "过", pinyin: "guò", meaning: "to pass, cross", strokes: 6, hsk: 3 },
  { char: "比", pinyin: "bǐ", meaning: "to compare", strokes: 4, hsk: 3 },
  { char: "较", pinyin: "jiào", meaning: "compare, rather", strokes: 10, hsk: 3 },
  { char: "最", pinyin: "zuì", meaning: "most, -est", strokes: 12, hsk: 3 },
  { char: "更", pinyin: "gèng", meaning: "even more", strokes: 7, hsk: 3 },
  { char: "非", pinyin: "fēi", meaning: "not, non-", strokes: 8, hsk: 3 },
  { char: "常", pinyin: "cháng", meaning: "often, normal", strokes: 11, hsk: 3 },
  { char: "特", pinyin: "tè", meaning: "special", strokes: 10, hsk: 3 },
  { char: "别", pinyin: "bié", meaning: "don't, other", strokes: 7, hsk: 3 },
  { char: "重", pinyin: "zhòng", meaning: "heavy, important", strokes: 9, hsk: 3 },
  { char: "轻", pinyin: "qīng", meaning: "light (weight)", strokes: 9, hsk: 3 },
  { char: "真", pinyin: "zhēn", meaning: "true, real", strokes: 10, hsk: 3 },
  { char: "假", pinyin: "jiǎ", meaning: "false, fake", strokes: 11, hsk: 3 },
  { char: "安", pinyin: "ān", meaning: "peace, safe", strokes: 6, hsk: 3 },
  { char: "全", pinyin: "quán", meaning: "complete, whole", strokes: 6, hsk: 3 },
  { char: "危", pinyin: "wēi", meaning: "danger", strokes: 6, hsk: 3 },
  { char: "险", pinyin: "xiǎn", meaning: "danger, risk", strokes: 9, hsk: 3 },
  { char: "力", pinyin: "lì", meaning: "power, strength", strokes: 2, hsk: 3 },
  { char: "动", pinyin: "dòng", meaning: "to move, action", strokes: 6, hsk: 3 },
  { char: "静", pinyin: "jìng", meaning: "quiet, calm", strokes: 14, hsk: 3 },
  { char: "难", pinyin: "nán", meaning: "difficult, hard", strokes: 10, hsk: 3 },
  { char: "容", pinyin: "róng", meaning: "appearance, allow", strokes: 10, hsk: 3 },
  { char: "易", pinyin: "yì", meaning: "easy, change", strokes: 8, hsk: 3 },
  { char: "简", pinyin: "jiǎn", meaning: "simple", strokes: 13, hsk: 3 },
  { char: "单", pinyin: "dān", meaning: "single, simple", strokes: 8, hsk: 3 },
  { char: "复", pinyin: "fù", meaning: "complex, repeat", strokes: 9, hsk: 3 },
  { char: "杂", pinyin: "zá", meaning: "mixed, complex", strokes: 6, hsk: 3 },
  { char: "世", pinyin: "shì", meaning: "world, era", strokes: 5, hsk: 3 },
  { char: "界", pinyin: "jiè", meaning: "boundary, world", strokes: 9, hsk: 3 },
  { char: "国", pinyin: "guó", meaning: "country, nation", strokes: 8, hsk: 3 },
  { char: "城", pinyin: "chéng", meaning: "city", strokes: 9, hsk: 3 },
  { char: "市", pinyin: "shì", meaning: "city, market", strokes: 5, hsk: 3 },
  { char: "园", pinyin: "yuán", meaning: "garden, park", strokes: 7, hsk: 3 },
  { char: "地", pinyin: "dì", meaning: "earth, ground", strokes: 6, hsk: 3 },
  { char: "方", pinyin: "fāng", meaning: "direction, square", strokes: 4, hsk: 3 },
  { char: "位", pinyin: "wèi", meaning: "position, seat", strokes: 7, hsk: 3 },
  { char: "站", pinyin: "zhàn", meaning: "station, stand", strokes: 10, hsk: 3 },
  { char: "考", pinyin: "kǎo", meaning: "exam, test", strokes: 6, hsk: 3 },
  { char: "试", pinyin: "shì", meaning: "to try, test", strokes: 8, hsk: 3 },
  { char: "题", pinyin: "tí", meaning: "topic, question", strokes: 15, hsk: 3 },

  // ─── HSK 4 (80 characters) ───
  { char: "梦", pinyin: "mèng", meaning: "dream", strokes: 11, hsk: 4 },
  { char: "勇", pinyin: "yǒng", meaning: "brave, courageous", strokes: 9, hsk: 4 },
  { char: "敢", pinyin: "gǎn", meaning: "to dare", strokes: 11, hsk: 4 },
  { char: "温", pinyin: "wēn", meaning: "warm, temperature", strokes: 12, hsk: 4 },
  { char: "度", pinyin: "dù", meaning: "degree, measure", strokes: 9, hsk: 4 },
  { char: "冷", pinyin: "lěng", meaning: "cold", strokes: 7, hsk: 4 },
  { char: "热", pinyin: "rè", meaning: "hot, heat", strokes: 10, hsk: 4 },
  { char: "风", pinyin: "fēng", meaning: "wind", strokes: 4, hsk: 4 },
  { char: "雨", pinyin: "yǔ", meaning: "rain", strokes: 8, hsk: 4 },
  { char: "雪", pinyin: "xuě", meaning: "snow", strokes: 11, hsk: 4 },
  { char: "云", pinyin: "yún", meaning: "cloud", strokes: 4, hsk: 4 },
  { char: "春", pinyin: "chūn", meaning: "spring", strokes: 9, hsk: 4 },
  { char: "夏", pinyin: "xià", meaning: "summer", strokes: 10, hsk: 4 },
  { char: "秋", pinyin: "qiū", meaning: "autumn", strokes: 9, hsk: 4 },
  { char: "冬", pinyin: "dōng", meaning: "winter", strokes: 5, hsk: 4 },
  { char: "海", pinyin: "hǎi", meaning: "sea, ocean", strokes: 10, hsk: 4 },
  { char: "湖", pinyin: "hú", meaning: "lake", strokes: 12, hsk: 4 },
  { char: "岛", pinyin: "dǎo", meaning: "island", strokes: 7, hsk: 4 },
  { char: "森", pinyin: "sēn", meaning: "forest", strokes: 12, hsk: 4 },
  { char: "林", pinyin: "lín", meaning: "forest, woods", strokes: 8, hsk: 4 },
  { char: "草", pinyin: "cǎo", meaning: "grass", strokes: 9, hsk: 4 },
  { char: "叶", pinyin: "yè", meaning: "leaf", strokes: 5, hsk: 4 },
  { char: "石", pinyin: "shí", meaning: "stone, rock", strokes: 5, hsk: 4 },
  { char: "土", pinyin: "tǔ", meaning: "earth, soil", strokes: 3, hsk: 4 },
  { char: "金", pinyin: "jīn", meaning: "gold, metal", strokes: 8, hsk: 4 },
  { char: "银", pinyin: "yín", meaning: "silver", strokes: 11, hsk: 4 },
  { char: "铁", pinyin: "tiě", meaning: "iron", strokes: 10, hsk: 4 },
  { char: "光", pinyin: "guāng", meaning: "light, ray", strokes: 6, hsk: 4 },
  { char: "影", pinyin: "yǐng", meaning: "shadow, movie", strokes: 15, hsk: 4 },
  { char: "音", pinyin: "yīn", meaning: "sound", strokes: 9, hsk: 4 },
  { char: "乐", pinyin: "yuè", meaning: "music, happy", strokes: 5, hsk: 4 },
  { char: "画", pinyin: "huà", meaning: "to draw, painting", strokes: 8, hsk: 4 },
  { char: "色", pinyin: "sè", meaning: "color", strokes: 6, hsk: 4 },
  { char: "青", pinyin: "qīng", meaning: "green, youth", strokes: 8, hsk: 4 },
  { char: "蓝", pinyin: "lán", meaning: "blue", strokes: 13, hsk: 4 },
  { char: "黄", pinyin: "huáng", meaning: "yellow", strokes: 11, hsk: 4 },
  { char: "绿", pinyin: "lǜ", meaning: "green", strokes: 11, hsk: 4 },
  { char: "紫", pinyin: "zǐ", meaning: "purple", strokes: 12, hsk: 4 },
  { char: "疼", pinyin: "téng", meaning: "pain, ache", strokes: 10, hsk: 4 },
  { char: "病", pinyin: "bìng", meaning: "illness, sick", strokes: 10, hsk: 4 },
  { char: "药", pinyin: "yào", meaning: "medicine", strokes: 9, hsk: 4 },
  { char: "医", pinyin: "yī", meaning: "doctor, medicine", strokes: 7, hsk: 4 },
  { char: "院", pinyin: "yuàn", meaning: "courtyard, hospital", strokes: 9, hsk: 4 },
  { char: "科", pinyin: "kē", meaning: "science, dept", strokes: 9, hsk: 4 },
  { char: "技", pinyin: "jì", meaning: "skill, technology", strokes: 7, hsk: 4 },
  { char: "术", pinyin: "shù", meaning: "art, skill", strokes: 5, hsk: 4 },
  { char: "算", pinyin: "suàn", meaning: "to count, calculate", strokes: 14, hsk: 4 },
  { char: "研", pinyin: "yán", meaning: "to study, research", strokes: 9, hsk: 4 },
  { char: "究", pinyin: "jiū", meaning: "to investigate", strokes: 7, hsk: 4 },
  { char: "结", pinyin: "jié", meaning: "to tie, result", strokes: 9, hsk: 4 },
  { char: "果", pinyin: "guǒ", meaning: "fruit, result", strokes: 8, hsk: 4 },
  { char: "成", pinyin: "chéng", meaning: "to become, succeed", strokes: 6, hsk: 4 },
  { char: "功", pinyin: "gōng", meaning: "merit, success", strokes: 5, hsk: 4 },
  { char: "失", pinyin: "shī", meaning: "to lose, fail", strokes: 5, hsk: 4 },
  { char: "败", pinyin: "bài", meaning: "to defeat, fail", strokes: 8, hsk: 4 },
  { char: "赢", pinyin: "yíng", meaning: "to win", strokes: 17, hsk: 4 },
  { char: "输", pinyin: "shū", meaning: "to lose, transport", strokes: 13, hsk: 4 },
  { char: "选", pinyin: "xuǎn", meaning: "to choose, select", strokes: 9, hsk: 4 },
  { char: "择", pinyin: "zé", meaning: "to choose, pick", strokes: 8, hsk: 4 },
  { char: "愿", pinyin: "yuàn", meaning: "wish, willing", strokes: 14, hsk: 4 },
  { char: "望", pinyin: "wàng", meaning: "to hope, gaze", strokes: 11, hsk: 4 },
  { char: "忘", pinyin: "wàng", meaning: "to forget", strokes: 7, hsk: 4 },
  { char: "记", pinyin: "jì", meaning: "to remember, note", strokes: 5, hsk: 4 },
  { char: "忆", pinyin: "yì", meaning: "to recall, memory", strokes: 4, hsk: 4 },
  { char: "思", pinyin: "sī", meaning: "to think, miss", strokes: 9, hsk: 4 },
  { char: "念", pinyin: "niàn", meaning: "to read, miss", strokes: 8, hsk: 4 },
  { char: "怕", pinyin: "pà", meaning: "to fear, afraid", strokes: 8, hsk: 4 },
  { char: "惊", pinyin: "jīng", meaning: "surprise, shock", strokes: 11, hsk: 4 },
  { char: "喜", pinyin: "xǐ", meaning: "happy, joy", strokes: 12, hsk: 4 },
  { char: "悲", pinyin: "bēi", meaning: "sad, sorrow", strokes: 12, hsk: 4 },
  { char: "怒", pinyin: "nù", meaning: "anger, fury", strokes: 9, hsk: 4 },
  { char: "恐", pinyin: "kǒng", meaning: "fear, dread", strokes: 10, hsk: 4 },
  { char: "惧", pinyin: "jù", meaning: "fear, dread", strokes: 11, hsk: 4 },
  { char: "永", pinyin: "yǒng", meaning: "eternal, forever", strokes: 5, hsk: 4 },
  { char: "久", pinyin: "jiǔ", meaning: "long time", strokes: 3, hsk: 4 },
  { char: "短", pinyin: "duǎn", meaning: "short", strokes: 12, hsk: 4 },
  { char: "深", pinyin: "shēn", meaning: "deep, profound", strokes: 11, hsk: 4 },
  { char: "浅", pinyin: "qiǎn", meaning: "shallow", strokes: 8, hsk: 4 },
  { char: "宽", pinyin: "kuān", meaning: "wide, broad", strokes: 10, hsk: 4 },
  { char: "窄", pinyin: "zhǎi", meaning: "narrow", strokes: 10, hsk: 4 },

  // ─── HSK 5 (120 characters) ───
  { char: "承", pinyin: "chéng", meaning: "to bear, undertake", strokes: 8, hsk: 5 },
  { char: "担", pinyin: "dān", meaning: "to carry, bear", strokes: 8, hsk: 5 },
  { char: "责", pinyin: "zé", meaning: "responsibility", strokes: 8, hsk: 5 },
  { char: "任", pinyin: "rèn", meaning: "duty, appoint", strokes: 6, hsk: 5 },
  { char: "态", pinyin: "tài", meaning: "attitude, state", strokes: 8, hsk: 5 },
  { char: "势", pinyin: "shì", meaning: "power, tendency", strokes: 8, hsk: 5 },
  { char: "状", pinyin: "zhuàng", meaning: "shape, condition", strokes: 7, hsk: 5 },
  { char: "况", pinyin: "kuàng", meaning: "situation", strokes: 7, hsk: 5 },
  { char: "辩", pinyin: "biàn", meaning: "to argue, debate", strokes: 16, hsk: 5 },
  { char: "论", pinyin: "lùn", meaning: "to discuss, theory", strokes: 6, hsk: 5 },
  { char: "证", pinyin: "zhèng", meaning: "evidence, prove", strokes: 7, hsk: 5 },
  { char: "据", pinyin: "jù", meaning: "evidence, basis", strokes: 11, hsk: 5 },
  { char: "判", pinyin: "pàn", meaning: "to judge", strokes: 7, hsk: 5 },
  { char: "断", pinyin: "duàn", meaning: "to break, judge", strokes: 11, hsk: 5 },
  { char: "观", pinyin: "guān", meaning: "to observe, view", strokes: 6, hsk: 5 },
  { char: "察", pinyin: "chá", meaning: "to examine", strokes: 14, hsk: 5 },
  { char: "探", pinyin: "tàn", meaning: "to explore, probe", strokes: 11, hsk: 5 },
  { char: "索", pinyin: "suǒ", meaning: "to search, rope", strokes: 10, hsk: 5 },
  { char: "追", pinyin: "zhuī", meaning: "to chase, pursue", strokes: 9, hsk: 5 },
  { char: "求", pinyin: "qiú", meaning: "to seek, request", strokes: 7, hsk: 5 },
  { char: "获", pinyin: "huò", meaning: "to obtain, harvest", strokes: 10, hsk: 5 },
  { char: "奖", pinyin: "jiǎng", meaning: "award, prize", strokes: 9, hsk: 5 },
  { char: "赏", pinyin: "shǎng", meaning: "to appreciate", strokes: 12, hsk: 5 },
  { char: "罚", pinyin: "fá", meaning: "to punish, fine", strokes: 9, hsk: 5 },
  { char: "制", pinyin: "zhì", meaning: "system, to make", strokes: 8, hsk: 5 },
  { char: "造", pinyin: "zào", meaning: "to create, build", strokes: 10, hsk: 5 },
  { char: "建", pinyin: "jiàn", meaning: "to build, establish", strokes: 8, hsk: 5 },
  { char: "设", pinyin: "shè", meaning: "to set up, design", strokes: 6, hsk: 5 },
  { char: "修", pinyin: "xiū", meaning: "to repair, study", strokes: 9, hsk: 5 },
  { char: "改", pinyin: "gǎi", meaning: "to change, reform", strokes: 7, hsk: 5 },
  { char: "革", pinyin: "gé", meaning: "leather, reform", strokes: 9, hsk: 5 },
  { char: "创", pinyin: "chuàng", meaning: "to create, innovate", strokes: 6, hsk: 5 },
  { char: "破", pinyin: "pò", meaning: "to break, destroy", strokes: 10, hsk: 5 },
  { char: "毁", pinyin: "huǐ", meaning: "to destroy, ruin", strokes: 13, hsk: 5 },
  { char: "灭", pinyin: "miè", meaning: "to extinguish", strokes: 5, hsk: 5 },
  { char: "救", pinyin: "jiù", meaning: "to rescue, save", strokes: 11, hsk: 5 },
  { char: "护", pinyin: "hù", meaning: "to protect", strokes: 7, hsk: 5 },
  { char: "防", pinyin: "fáng", meaning: "to defend, prevent", strokes: 6, hsk: 5 },
  { char: "御", pinyin: "yù", meaning: "to defend, resist", strokes: 12, hsk: 5 },
  { char: "攻", pinyin: "gōng", meaning: "to attack", strokes: 7, hsk: 5 },
  { char: "击", pinyin: "jī", meaning: "to strike, hit", strokes: 5, hsk: 5 },
  { char: "战", pinyin: "zhàn", meaning: "war, battle", strokes: 9, hsk: 5 },
  { char: "争", pinyin: "zhēng", meaning: "to compete, argue", strokes: 6, hsk: 5 },
  { char: "胜", pinyin: "shèng", meaning: "to win, victory", strokes: 9, hsk: 5 },
  { char: "负", pinyin: "fù", meaning: "negative, to lose", strokes: 6, hsk: 5 },
  { char: "降", pinyin: "jiàng", meaning: "to descend, drop", strokes: 8, hsk: 5 },
  { char: "升", pinyin: "shēng", meaning: "to rise, promote", strokes: 4, hsk: 5 },
  { char: "增", pinyin: "zēng", meaning: "to increase", strokes: 15, hsk: 5 },
  { char: "减", pinyin: "jiǎn", meaning: "to reduce, minus", strokes: 11, hsk: 5 },
  { char: "积", pinyin: "jī", meaning: "to accumulate", strokes: 10, hsk: 5 },
  { char: "累", pinyin: "lèi", meaning: "tired, to accumulate", strokes: 11, hsk: 5 },
  { char: "均", pinyin: "jūn", meaning: "equal, even", strokes: 7, hsk: 5 },
  { char: "衡", pinyin: "héng", meaning: "balance, weigh", strokes: 16, hsk: 5 },
  { char: "稳", pinyin: "wěn", meaning: "stable, steady", strokes: 14, hsk: 5 },
  { char: "固", pinyin: "gù", meaning: "solid, firm", strokes: 8, hsk: 5 },
  { char: "坚", pinyin: "jiān", meaning: "hard, firm", strokes: 7, hsk: 5 },
  { char: "强", pinyin: "qiáng", meaning: "strong, powerful", strokes: 12, hsk: 5 },
  { char: "弱", pinyin: "ruò", meaning: "weak", strokes: 10, hsk: 5 },
  { char: "猛", pinyin: "měng", meaning: "fierce, violent", strokes: 11, hsk: 5 },
  { char: "烈", pinyin: "liè", meaning: "intense, ardent", strokes: 10, hsk: 5 },
  { char: "柔", pinyin: "róu", meaning: "soft, gentle", strokes: 9, hsk: 5 },
  { char: "软", pinyin: "ruǎn", meaning: "soft, flexible", strokes: 8, hsk: 5 },
  { char: "硬", pinyin: "yìng", meaning: "hard, stiff", strokes: 12, hsk: 5 },
  { char: "脆", pinyin: "cuì", meaning: "crisp, fragile", strokes: 10, hsk: 5 },
  { char: "粗", pinyin: "cū", meaning: "thick, coarse", strokes: 11, hsk: 5 },
  { char: "细", pinyin: "xì", meaning: "thin, fine", strokes: 8, hsk: 5 },
  { char: "厚", pinyin: "hòu", meaning: "thick, generous", strokes: 9, hsk: 5 },
  { char: "薄", pinyin: "bó", meaning: "thin, weak", strokes: 16, hsk: 5 },
  { char: "密", pinyin: "mì", meaning: "dense, secret", strokes: 11, hsk: 5 },
  { char: "繁", pinyin: "fán", meaning: "complex, numerous", strokes: 17, hsk: 5 },
  { char: "荣", pinyin: "róng", meaning: "glory, flourish", strokes: 9, hsk: 5 },
  { char: "鲜", pinyin: "xiān", meaning: "fresh, vivid", strokes: 14, hsk: 5 },
  { char: "净", pinyin: "jìng", meaning: "clean, pure", strokes: 8, hsk: 5 },
  { char: "善", pinyin: "shàn", meaning: "good, kind", strokes: 12, hsk: 5 },
  { char: "恶", pinyin: "è", meaning: "evil, wicked", strokes: 10, hsk: 5 },
  { char: "谦", pinyin: "qiān", meaning: "modest, humble", strokes: 12, hsk: 5 },
  { char: "傲", pinyin: "ào", meaning: "proud, arrogant", strokes: 12, hsk: 5 },
  { char: "尊", pinyin: "zūn", meaning: "respect, honor", strokes: 12, hsk: 5 },
  { char: "忠", pinyin: "zhōng", meaning: "loyal, faithful", strokes: 8, hsk: 5 },
  { char: "诚", pinyin: "chéng", meaning: "sincere, honest", strokes: 8, hsk: 5 },
  { char: "慧", pinyin: "huì", meaning: "wisdom, intelligent", strokes: 15, hsk: 5 },
  { char: "灵", pinyin: "líng", meaning: "spirit, clever", strokes: 7, hsk: 5 },
  { char: "志", pinyin: "zhì", meaning: "ambition, will", strokes: 7, hsk: 5 },
  { char: "趣", pinyin: "qù", meaning: "interest, fun", strokes: 15, hsk: 5 },
  { char: "味", pinyin: "wèi", meaning: "taste, flavor", strokes: 8, hsk: 5 },
  { char: "香", pinyin: "xiāng", meaning: "fragrant, incense", strokes: 9, hsk: 5 },
  { char: "甜", pinyin: "tián", meaning: "sweet", strokes: 11, hsk: 5 },
  { char: "苦", pinyin: "kǔ", meaning: "bitter, hard", strokes: 8, hsk: 5 },
  { char: "酸", pinyin: "suān", meaning: "sour, acid", strokes: 14, hsk: 5 },
  { char: "辣", pinyin: "là", meaning: "spicy, hot", strokes: 14, hsk: 5 },
  { char: "咸", pinyin: "xián", meaning: "salty", strokes: 9, hsk: 5 },
  { char: "淡", pinyin: "dàn", meaning: "bland, light", strokes: 11, hsk: 5 },
  { char: "饱", pinyin: "bǎo", meaning: "full (stomach)", strokes: 8, hsk: 5 },
  { char: "饿", pinyin: "è", meaning: "hungry", strokes: 10, hsk: 5 },
  { char: "渴", pinyin: "kě", meaning: "thirsty", strokes: 12, hsk: 5 },
  { char: "醉", pinyin: "zuì", meaning: "drunk", strokes: 15, hsk: 5 },
  { char: "醒", pinyin: "xǐng", meaning: "to wake up", strokes: 16, hsk: 5 },
  { char: "困", pinyin: "kùn", meaning: "sleepy, trapped", strokes: 7, hsk: 5 },
  { char: "恢", pinyin: "huī", meaning: "to restore", strokes: 9, hsk: 5 },
  { char: "摧", pinyin: "cuī", meaning: "to destroy, crush", strokes: 14, hsk: 5 },
  { char: "折", pinyin: "zhé", meaning: "to break, fold", strokes: 7, hsk: 5 },
  { char: "弃", pinyin: "qì", meaning: "to abandon, discard", strokes: 7, hsk: 5 },
  { char: "抛", pinyin: "pāo", meaning: "to throw, abandon", strokes: 7, hsk: 5 },
  { char: "捕", pinyin: "bǔ", meaning: "to catch, arrest", strokes: 10, hsk: 5 },
  { char: "捉", pinyin: "zhuō", meaning: "to catch, seize", strokes: 10, hsk: 5 },
  { char: "握", pinyin: "wò", meaning: "to grasp, hold", strokes: 12, hsk: 5 },
  { char: "抓", pinyin: "zhuā", meaning: "to grab, scratch", strokes: 7, hsk: 5 },
  { char: "挥", pinyin: "huī", meaning: "to wave, wield", strokes: 9, hsk: 5 },
  { char: "拍", pinyin: "pāi", meaning: "to pat, clap", strokes: 8, hsk: 5 },
  { char: "揭", pinyin: "jiē", meaning: "to reveal, expose", strokes: 12, hsk: 5 },
  { char: "披", pinyin: "pī", meaning: "to drape, open", strokes: 8, hsk: 5 },
  { char: "裹", pinyin: "guǒ", meaning: "to wrap, bind", strokes: 14, hsk: 5 },
  { char: "缠", pinyin: "chán", meaning: "to wind, tangle", strokes: 13, hsk: 5 },
  { char: "绕", pinyin: "rào", meaning: "to wind around", strokes: 9, hsk: 5 },
  { char: "绑", pinyin: "bǎng", meaning: "to tie, bind", strokes: 9, hsk: 5 },
  { char: "拴", pinyin: "shuān", meaning: "to tie, fasten", strokes: 9, hsk: 5 },
  { char: "锁", pinyin: "suǒ", meaning: "lock, to lock", strokes: 12, hsk: 5 },

  // ─── HSK 6 (120 characters) ───
  { char: "瞻", pinyin: "zhān", meaning: "to gaze, look up", strokes: 18, hsk: 6 },
  { char: "仰", pinyin: "yǎng", meaning: "to look up, admire", strokes: 6, hsk: 6 },
  { char: "俯", pinyin: "fǔ", meaning: "to look down, bow", strokes: 10, hsk: 6 },
  { char: "凝", pinyin: "níng", meaning: "to congeal, stare", strokes: 16, hsk: 6 },
  { char: "眺", pinyin: "tiào", meaning: "to gaze far", strokes: 11, hsk: 6 },
  { char: "窥", pinyin: "kuī", meaning: "to peep, spy", strokes: 13, hsk: 6 },
  { char: "睹", pinyin: "dǔ", meaning: "to see, witness", strokes: 13, hsk: 6 },
  { char: "聆", pinyin: "líng", meaning: "to listen carefully", strokes: 11, hsk: 6 },
  { char: "嘱", pinyin: "zhǔ", meaning: "to enjoin, advise", strokes: 15, hsk: 6 },
  { char: "嘲", pinyin: "cháo", meaning: "to ridicule, mock", strokes: 15, hsk: 6 },
  { char: "讽", pinyin: "fěng", meaning: "to satirize", strokes: 6, hsk: 6 },
  { char: "谴", pinyin: "qiǎn", meaning: "to condemn", strokes: 15, hsk: 6 },
  { char: "斥", pinyin: "chì", meaning: "to scold, repel", strokes: 5, hsk: 6 },
  { char: "辱", pinyin: "rǔ", meaning: "disgrace, insult", strokes: 10, hsk: 6 },
  { char: "蔑", pinyin: "miè", meaning: "to despise, scorn", strokes: 14, hsk: 6 },
  { char: "鄙", pinyin: "bǐ", meaning: "to despise, vulgar", strokes: 13, hsk: 6 },
  { char: "渊", pinyin: "yuān", meaning: "abyss, deep pool", strokes: 11, hsk: 6 },
  { char: "博", pinyin: "bó", meaning: "broad, extensive", strokes: 12, hsk: 6 },
  { char: "涵", pinyin: "hán", meaning: "contain, restrain", strokes: 11, hsk: 6 },
  { char: "蕴", pinyin: "yùn", meaning: "to contain, store up", strokes: 15, hsk: 6 },
  { char: "蓄", pinyin: "xù", meaning: "to store, save up", strokes: 13, hsk: 6 },
  { char: "储", pinyin: "chǔ", meaning: "to store, deposit", strokes: 12, hsk: 6 },
  { char: "藏", pinyin: "cáng", meaning: "to hide, store", strokes: 17, hsk: 6 },
  { char: "匿", pinyin: "nì", meaning: "to hide, conceal", strokes: 10, hsk: 6 },
  { char: "隐", pinyin: "yǐn", meaning: "hidden, secret", strokes: 11, hsk: 6 },
  { char: "遮", pinyin: "zhē", meaning: "to block, cover", strokes: 14, hsk: 6 },
  { char: "掩", pinyin: "yǎn", meaning: "to cover, hide", strokes: 11, hsk: 6 },
  { char: "障", pinyin: "zhàng", meaning: "barrier, obstacle", strokes: 13, hsk: 6 },
  { char: "碍", pinyin: "ài", meaning: "to hinder, block", strokes: 13, hsk: 6 },
  { char: "阻", pinyin: "zǔ", meaning: "to block, hinder", strokes: 7, hsk: 6 },
  { char: "扰", pinyin: "rǎo", meaning: "to disturb, harass", strokes: 7, hsk: 6 },
  { char: "惑", pinyin: "huò", meaning: "to confuse, doubt", strokes: 12, hsk: 6 },
  { char: "迷", pinyin: "mí", meaning: "to be lost, fan", strokes: 9, hsk: 6 },
  { char: "哀", pinyin: "āi", meaning: "sorrow, pity", strokes: 9, hsk: 6 },
  { char: "泣", pinyin: "qì", meaning: "to weep, sob", strokes: 8, hsk: 6 },
  { char: "憩", pinyin: "qì", meaning: "to rest, repose", strokes: 16, hsk: 6 },
  { char: "懈", pinyin: "xiè", meaning: "to slack, relax", strokes: 16, hsk: 6 },
  { char: "怠", pinyin: "dài", meaning: "idle, neglect", strokes: 9, hsk: 6 },
  { char: "驱", pinyin: "qū", meaning: "to drive, expel", strokes: 7, hsk: 6 },
  { char: "逐", pinyin: "zhú", meaning: "to chase, pursue", strokes: 10, hsk: 6 },
  { char: "遣", pinyin: "qiǎn", meaning: "to dispatch, send", strokes: 13, hsk: 6 },
  { char: "禁", pinyin: "jìn", meaning: "to prohibit", strokes: 13, hsk: 6 },
  { char: "囚", pinyin: "qiú", meaning: "prisoner, to imprison", strokes: 5, hsk: 6 },
  { char: "赦", pinyin: "shè", meaning: "to pardon, forgive", strokes: 11, hsk: 6 },
  { char: "恕", pinyin: "shù", meaning: "to forgive, pardon", strokes: 10, hsk: 6 },
  { char: "饶", pinyin: "ráo", meaning: "to forgive, rich", strokes: 9, hsk: 6 },
  { char: "宏", pinyin: "hóng", meaning: "grand, magnificent", strokes: 7, hsk: 6 },
  { char: "伟", pinyin: "wěi", meaning: "great, mighty", strokes: 6, hsk: 6 },
  { char: "壮", pinyin: "zhuàng", meaning: "strong, robust", strokes: 6, hsk: 6 },
  { char: "雄", pinyin: "xióng", meaning: "male, heroic", strokes: 12, hsk: 6 },
  { char: "豪", pinyin: "háo", meaning: "heroic, bold", strokes: 14, hsk: 6 },
  { char: "杰", pinyin: "jié", meaning: "outstanding, hero", strokes: 8, hsk: 6 },
  { char: "卓", pinyin: "zhuó", meaning: "outstanding, tall", strokes: 8, hsk: 6 },
  { char: "超", pinyin: "chāo", meaning: "to surpass, super", strokes: 12, hsk: 6 },
  { char: "凡", pinyin: "fán", meaning: "ordinary, mortal", strokes: 3, hsk: 6 },
  { char: "拙", pinyin: "zhuō", meaning: "clumsy, poor", strokes: 8, hsk: 6 },
  { char: "巧", pinyin: "qiǎo", meaning: "skillful, clever", strokes: 5, hsk: 6 },
  { char: "妙", pinyin: "miào", meaning: "wonderful, clever", strokes: 7, hsk: 6 },
  { char: "奇", pinyin: "qí", meaning: "strange, wonderful", strokes: 8, hsk: 6 },
  { char: "怪", pinyin: "guài", meaning: "strange, monster", strokes: 8, hsk: 6 },
  { char: "幻", pinyin: "huàn", meaning: "illusion, fantasy", strokes: 4, hsk: 6 },
  { char: "虚", pinyin: "xū", meaning: "empty, false", strokes: 11, hsk: 6 },
  { char: "骗", pinyin: "piàn", meaning: "to deceive, trick", strokes: 12, hsk: 6 },
  { char: "陷", pinyin: "xiàn", meaning: "to trap, fall into", strokes: 10, hsk: 6 },
  { char: "溺", pinyin: "nì", meaning: "to drown, indulge", strokes: 13, hsk: 6 },
  { char: "沦", pinyin: "lún", meaning: "to sink, degrade", strokes: 7, hsk: 6 },
  { char: "衰", pinyin: "shuāi", meaning: "to decline, weak", strokes: 10, hsk: 6 },
  { char: "朽", pinyin: "xiǔ", meaning: "rotten, decayed", strokes: 6, hsk: 6 },
  { char: "辉", pinyin: "huī", meaning: "splendor, radiance", strokes: 12, hsk: 6 },
  { char: "耀", pinyin: "yào", meaning: "to shine, dazzle", strokes: 20, hsk: 6 },
  { char: "灿", pinyin: "càn", meaning: "brilliant, bright", strokes: 7, hsk: 6 },
  { char: "焕", pinyin: "huàn", meaning: "brilliant, radiant", strokes: 11, hsk: 6 },
  { char: "悠", pinyin: "yōu", meaning: "long, remote", strokes: 11, hsk: 6 },
  { char: "穆", pinyin: "mù", meaning: "solemn, reverent", strokes: 16, hsk: 6 },
  { char: "肃", pinyin: "sù", meaning: "solemn, respectful", strokes: 8, hsk: 6 },
  { char: "庄", pinyin: "zhuāng", meaning: "village, solemn", strokes: 6, hsk: 6 },
  { char: "典", pinyin: "diǎn", meaning: "classic, ceremony", strokes: 8, hsk: 6 },
  { char: "雅", pinyin: "yǎ", meaning: "elegant, refined", strokes: 12, hsk: 6 },
  { char: "俗", pinyin: "sú", meaning: "vulgar, custom", strokes: 9, hsk: 6 },
  { char: "朴", pinyin: "pǔ", meaning: "plain, simple", strokes: 6, hsk: 6 },
  { char: "素", pinyin: "sù", meaning: "element, plain", strokes: 10, hsk: 6 },
  { char: "雕", pinyin: "diāo", meaning: "to carve, sculpture", strokes: 16, hsk: 6 },
  { char: "塑", pinyin: "sù", meaning: "to model, plastic", strokes: 13, hsk: 6 },
  { char: "铸", pinyin: "zhù", meaning: "to cast (metal)", strokes: 12, hsk: 6 },
  { char: "锻", pinyin: "duàn", meaning: "to forge, temper", strokes: 14, hsk: 6 },
  { char: "炼", pinyin: "liàn", meaning: "to refine, smelt", strokes: 9, hsk: 6 },
  { char: "冶", pinyin: "yě", meaning: "to smelt, seduce", strokes: 7, hsk: 6 },
  { char: "磨", pinyin: "mó", meaning: "to grind, polish", strokes: 16, hsk: 6 },
  { char: "砺", pinyin: "lì", meaning: "whetstone, sharpen", strokes: 10, hsk: 6 },
  { char: "琢", pinyin: "zhuó", meaning: "to carve jade", strokes: 12, hsk: 6 },
  { char: "鉴", pinyin: "jiàn", meaning: "mirror, to examine", strokes: 13, hsk: 6 },
  { char: "赏", pinyin: "shǎng", meaning: "to appreciate", strokes: 12, hsk: 6 },
  { char: "析", pinyin: "xī", meaning: "to analyze, split", strokes: 8, hsk: 6 },
  { char: "辨", pinyin: "biàn", meaning: "to distinguish", strokes: 16, hsk: 6 },
  { char: "甄", pinyin: "zhēn", meaning: "to distinguish", strokes: 13, hsk: 6 },
  { char: "筛", pinyin: "shāi", meaning: "to sift, screen", strokes: 12, hsk: 6 },
  { char: "淘", pinyin: "táo", meaning: "to wash, eliminate", strokes: 11, hsk: 6 },
  { char: "汰", pinyin: "tài", meaning: "to eliminate", strokes: 7, hsk: 6 },
  { char: "涤", pinyin: "dí", meaning: "to wash, cleanse", strokes: 10, hsk: 6 },
  { char: "浸", pinyin: "jìn", meaning: "to soak, immerse", strokes: 10, hsk: 6 },
  { char: "润", pinyin: "rùn", meaning: "moist, smooth", strokes: 10, hsk: 6 },
  { char: "滋", pinyin: "zī", meaning: "to grow, nourish", strokes: 12, hsk: 6 },
  { char: "哺", pinyin: "bǔ", meaning: "to feed, nurse", strokes: 10, hsk: 6 },
  { char: "育", pinyin: "yù", meaning: "to raise, educate", strokes: 8, hsk: 6 },
  { char: "培", pinyin: "péi", meaning: "to cultivate", strokes: 11, hsk: 6 },
  { char: "栽", pinyin: "zāi", meaning: "to plant, grow", strokes: 10, hsk: 6 },
  { char: "植", pinyin: "zhí", meaning: "to plant, establish", strokes: 12, hsk: 6 },
  { char: "耕", pinyin: "gēng", meaning: "to plow, farm", strokes: 10, hsk: 6 },
  { char: "播", pinyin: "bō", meaning: "to sow, broadcast", strokes: 15, hsk: 6 },
  { char: "撒", pinyin: "sā", meaning: "to scatter, let go", strokes: 15, hsk: 6 },
  { char: "灌", pinyin: "guàn", meaning: "to irrigate, pour", strokes: 20, hsk: 6 },
  { char: "溉", pinyin: "gài", meaning: "to irrigate", strokes: 12, hsk: 6 },
  { char: "旱", pinyin: "hàn", meaning: "drought, dry", strokes: 7, hsk: 6 },
  { char: "涝", pinyin: "lào", meaning: "flood, waterlog", strokes: 10, hsk: 6 },
  { char: "沃", pinyin: "wò", meaning: "fertile, rich", strokes: 7, hsk: 6 },
  { char: "贫", pinyin: "pín", meaning: "poor, poverty", strokes: 8, hsk: 6 },
  { char: "瘠", pinyin: "jí", meaning: "barren, thin", strokes: 15, hsk: 6 },
];

// Create a default deck and seed all characters
const now = Math.floor(Date.now() / 1000);

// Get the first user from the DB
const firstUser = db.prepare('SELECT id FROM "user" LIMIT 1').get();

if (!firstUser) {
  console.log('⚠️  No users found. Please sign up first, then run this script.');
  process.exit(1);
}

const userId = firstUser.id;

// Group by HSK level and create decks
const hskLevels = [1, 2, 3, 4, 5, 6];
const deckIds = {};

const insertDeck = db.prepare('INSERT INTO decks (user_id, title, description, created_at) VALUES (?, ?, ?, ?)');
const insertCard = db.prepare('INSERT INTO flashcards (deck_id, character, pinyin, meaning, strokes, hsk_level, created_at) VALUES (?, ?, ?, ?, ?, ?, ?)');
const insertProgress = db.prepare('INSERT INTO user_progress (user_id, flashcard_id, interval, repetition, efactor, due_date) VALUES (?, ?, 0, 0, 2500, ?)');

const transaction = db.transaction(() => {
  for (const level of hskLevels) {
    const result = insertDeck.run(userId, `HSK ${level}`, `Official HSK Level ${level} characters`, now);
    deckIds[level] = result.lastInsertRowid;
  }

  let cardCount = 0;
  for (const c of characters) {
    const result = insertCard.run(deckIds[c.hsk], c.char, c.pinyin, c.meaning, c.strokes, c.hsk, now);
    insertProgress.run(userId, result.lastInsertRowid, now);
    cardCount++;
  }

  console.log(`✅ Seeded ${cardCount} characters across ${hskLevels.length} decks for user: ${userId}`);
});

transaction();
db.close();
