import { relations, sql } from "drizzle-orm";
import { sqliteTable, text, integer, index } from "drizzle-orm/sqlite-core";

// ─── Auth Tables (generated by better-auth CLI) ───

export const user = sqliteTable("user", {
  id: text("id").primaryKey(),
  name: text("name").notNull(),
  email: text("email").notNull().unique(),
  emailVerified: integer("email_verified", { mode: "boolean" })
    .default(false)
    .notNull(),
  image: text("image"),
  createdAt: integer("created_at", { mode: "timestamp_ms" })
    .default(sql`(cast(unixepoch('subsecond') * 1000 as integer))`)
    .notNull(),
  updatedAt: integer("updated_at", { mode: "timestamp_ms" })
    .default(sql`(cast(unixepoch('subsecond') * 1000 as integer))`)
    .$onUpdate(() => new Date())
    .notNull(),
});

export const session = sqliteTable(
  "session",
  {
    id: text("id").primaryKey(),
    expiresAt: integer("expires_at", { mode: "timestamp_ms" }).notNull(),
    token: text("token").notNull().unique(),
    createdAt: integer("created_at", { mode: "timestamp_ms" })
      .default(sql`(cast(unixepoch('subsecond') * 1000 as integer))`)
      .notNull(),
    updatedAt: integer("updated_at", { mode: "timestamp_ms" })
      .$onUpdate(() => new Date())
      .notNull(),
    ipAddress: text("ip_address"),
    userAgent: text("user_agent"),
    userId: text("user_id")
      .notNull()
      .references(() => user.id, { onDelete: "cascade" }),
  },
  (table) => [index("session_userId_idx").on(table.userId)],
);

export const account = sqliteTable(
  "account",
  {
    id: text("id").primaryKey(),
    accountId: text("account_id").notNull(),
    providerId: text("provider_id").notNull(),
    userId: text("user_id")
      .notNull()
      .references(() => user.id, { onDelete: "cascade" }),
    accessToken: text("access_token"),
    refreshToken: text("refresh_token"),
    idToken: text("id_token"),
    accessTokenExpiresAt: integer("access_token_expires_at", {
      mode: "timestamp_ms",
    }),
    refreshTokenExpiresAt: integer("refresh_token_expires_at", {
      mode: "timestamp_ms",
    }),
    scope: text("scope"),
    password: text("password"),
    createdAt: integer("created_at", { mode: "timestamp_ms" })
      .default(sql`(cast(unixepoch('subsecond') * 1000 as integer))`)
      .notNull(),
    updatedAt: integer("updated_at", { mode: "timestamp_ms" })
      .$onUpdate(() => new Date())
      .notNull(),
  },
  (table) => [index("account_userId_idx").on(table.userId)],
);

export const verification = sqliteTable(
  "verification",
  {
    id: text("id").primaryKey(),
    identifier: text("identifier").notNull(),
    value: text("value").notNull(),
    expiresAt: integer("expires_at", { mode: "timestamp_ms" }).notNull(),
    createdAt: integer("created_at", { mode: "timestamp_ms" })
      .default(sql`(cast(unixepoch('subsecond') * 1000 as integer))`)
      .notNull(),
    updatedAt: integer("updated_at", { mode: "timestamp_ms" })
      .default(sql`(cast(unixepoch('subsecond') * 1000 as integer))`)
      .$onUpdate(() => new Date())
      .notNull(),
  },
  (table) => [index("verification_identifier_idx").on(table.identifier)],
);

// ─── Auth Relations ───

export const userRelations = relations(user, ({ many }) => ({
  sessions: many(session),
  accounts: many(account),
}));

export const sessionRelations = relations(session, ({ one }) => ({
  user: one(user, {
    fields: [session.userId],
    references: [user.id],
  }),
}));

export const accountRelations = relations(account, ({ one }) => ({
  user: one(user, {
    fields: [account.userId],
    references: [user.id],
  }),
}));

// ─── App Tables ───

export const decks = sqliteTable("decks", {
  id: integer("id").primaryKey({ autoIncrement: true }),
  userId: text("user_id").references(() => user.id).notNull(),
  title: text("title").notNull(),
  description: text("description"),
  createdAt: integer("created_at", { mode: "timestamp" }).notNull().$defaultFn(() => new Date()),
});

export const flashcards = sqliteTable("flashcards", {
  id: integer("id").primaryKey({ autoIncrement: true }),
  deckId: integer("deck_id").references(() => decks.id, { onDelete: "cascade" }).notNull(),
  character: text("character").notNull(),
  pinyin: text("pinyin").notNull(),
  meaning: text("meaning").notNull(),
  strokes: integer("strokes"),
  hskLevel: integer("hsk_level"),
  createdAt: integer("created_at", { mode: "timestamp" }).notNull().$defaultFn(() => new Date()),
}, (table) => [
  index("flashcards_deckId_idx").on(table.deckId),
  index("flashcards_hskLevel_idx").on(table.hskLevel),
  index("flashcards_character_idx").on(table.character),
]);

export const userProgress = sqliteTable("user_progress", {
  id: integer("id").primaryKey({ autoIncrement: true }),
  userId: text("user_id").references(() => user.id, { onDelete: "cascade" }).notNull(),
  flashcardId: integer("flashcard_id").references(() => flashcards.id, { onDelete: "cascade" }).notNull(),
  interval: integer("interval").default(0).notNull(),
  repetition: integer("repetition").default(0).notNull(),
  efactor: integer("efactor").default(2500).notNull(),
  dueDate: integer("due_date", { mode: "timestamp" }).notNull().$defaultFn(() => new Date()),
}, (table) => [
  index("progress_userId_idx").on(table.userId),
  index("progress_dueDate_idx").on(table.userId, table.dueDate),
  index("progress_flashcardId_idx").on(table.flashcardId),
]);

export const studySessions = sqliteTable("study_sessions", {
  id: integer("id").primaryKey({ autoIncrement: true }),
  userId: text("user_id").references(() => user.id, { onDelete: "cascade" }).notNull(),
  date: text("date").notNull(), // YYYY-MM-DD
  cardsReviewed: integer("cards_reviewed").default(0).notNull(),
  cardsCorrect: integer("cards_correct").default(0).notNull(),
  studyMinutes: integer("study_minutes").default(0).notNull(),
  createdAt: integer("created_at", { mode: "timestamp" }).notNull().$defaultFn(() => new Date()),
}, (table) => [
  index("sessions_userId_idx").on(table.userId),
  index("sessions_date_idx").on(table.userId, table.date),
]);

export const reviewLogs = sqliteTable("review_logs", {
  id: integer("id").primaryKey({ autoIncrement: true }),
  userId: text("user_id").references(() => user.id, { onDelete: "cascade" }).notNull(),
  flashcardId: integer("flashcard_id").references(() => flashcards.id, { onDelete: "cascade" }).notNull(),
  quality: integer("quality").notNull(),
  responseTimeMs: integer("response_time_ms"),
  createdAt: integer("created_at", { mode: "timestamp" }).notNull().$defaultFn(() => new Date()),
}, (table) => [
  index("review_logs_userId_idx").on(table.userId),
  index("review_logs_createdAt_idx").on(table.userId, table.createdAt),
  index("review_logs_flashcardId_idx").on(table.flashcardId),
]);

// ─── Sentence Context ───

export const characterSentences = sqliteTable("character_sentences", {
  id: integer("id").primaryKey({ autoIncrement: true }),
  character: text("character").notNull(),
  sentence: text("sentence").notNull(),
  pinyin: text("pinyin").notNull(),
  translation: text("translation").notNull(),
  hskLevel: integer("hsk_level"),
}, (table) => [
  index("sentences_character_idx").on(table.character),
]);

// ─── Radical Breakdown ───

export const characterRadicals = sqliteTable("character_radicals", {
  id: integer("id").primaryKey({ autoIncrement: true }),
  character: text("character").notNull().unique(),
  radicals: text("radicals").notNull(), // JSON: [{radical, meaning, position}]
  decomposition: text("decomposition"), // e.g. "⿰女子"
  etymology: text("etymology"),
});

// ─── Notifications ───

export const notifications = sqliteTable("notifications", {
  id: integer("id").primaryKey({ autoIncrement: true }),
  userId: text("user_id").references(() => user.id, { onDelete: "cascade" }).notNull(),
  title: text("title").notNull(),
  message: text("message").notNull(),
  type: text("type").notNull(), // 'weekly_summary' | 'milestone' | 'streak' | 'reminder'
  read: integer("read", { mode: "boolean" }).default(false).notNull(),
  data: text("data"), // JSON for extra payload
  createdAt: integer("created_at", { mode: "timestamp" }).notNull().$defaultFn(() => new Date()),
}, (table) => [
  index("notifications_userId_idx").on(table.userId),
  index("notifications_read_idx").on(table.userId, table.read),
]);

// ─── Gamification: XP Tracking ───

export const userXP = sqliteTable("user_xp", {
  id: integer("id").primaryKey({ autoIncrement: true }),
  userId: text("user_id").references(() => user.id, { onDelete: "cascade" }).notNull().unique(),
  totalXP: integer("total_xp").default(0).notNull(),
  level: integer("level").default(1).notNull(),
  currentStreak: integer("current_streak").default(0).notNull(),
  longestStreak: integer("longest_streak").default(0).notNull(),
  lastStudyDate: text("last_study_date"), // YYYY-MM-DD
  updatedAt: integer("updated_at", { mode: "timestamp" }).notNull().$defaultFn(() => new Date()),
}, (table) => [
  index("user_xp_userId_idx").on(table.userId),
]);

// ─── Gamification: Achievements ───

export const userAchievements = sqliteTable("user_achievements", {
  id: integer("id").primaryKey({ autoIncrement: true }),
  userId: text("user_id").references(() => user.id, { onDelete: "cascade" }).notNull(),
  achievementKey: text("achievement_key").notNull(), // e.g. 'first_review', 'streak_7', 'hsk1_complete'
  unlockedAt: integer("unlocked_at", { mode: "timestamp" }).notNull().$defaultFn(() => new Date()),
}, (table) => [
  index("achievements_userId_idx").on(table.userId),
  index("achievements_key_idx").on(table.userId, table.achievementKey),
]);

// ─── Gamification: Daily Challenges ───

export const dailyChallenges = sqliteTable("daily_challenges", {
  id: integer("id").primaryKey({ autoIncrement: true }),
  userId: text("user_id").references(() => user.id, { onDelete: "cascade" }).notNull(),
  date: text("date").notNull(), // YYYY-MM-DD
  challengeType: text("challenge_type").notNull(), // 'review_count' | 'perfect_recall' | 'stroke_practice' | 'quiz_score'
  targetValue: integer("target_value").notNull(),
  currentValue: integer("current_value").default(0).notNull(),
  completed: integer("completed", { mode: "boolean" }).default(false).notNull(),
  xpReward: integer("xp_reward").default(50).notNull(),
  createdAt: integer("created_at", { mode: "timestamp" }).notNull().$defaultFn(() => new Date()),
}, (table) => [
  index("challenges_userId_date_idx").on(table.userId, table.date),
]);

// ─── Content: Compound Words ───

export const compoundWords = sqliteTable("compound_words", {
  id: integer("id").primaryKey({ autoIncrement: true }),
  character: text("character").notNull(),
  word: text("word").notNull(),
  pinyin: text("pinyin").notNull(),
  meaning: text("meaning").notNull(),
  hskLevel: integer("hsk_level"),
}, (table) => [
  index("compound_words_char_idx").on(table.character),
]);

// ─── App Relations ───

export const decksRelations = relations(decks, ({ one, many }) => ({
  user: one(user, { fields: [decks.userId], references: [user.id] }),
  flashcards: many(flashcards),
}));

export const flashcardsRelations = relations(flashcards, ({ one }) => ({
  deck: one(decks, { fields: [flashcards.deckId], references: [decks.id] }),
}));

export const userProgressRelations = relations(userProgress, ({ one }) => ({
  user: one(user, { fields: [userProgress.userId], references: [user.id] }),
  flashcard: one(flashcards, { fields: [userProgress.flashcardId], references: [flashcards.id] }),
}));

export const studySessionsRelations = relations(studySessions, ({ one }) => ({
  user: one(user, { fields: [studySessions.userId], references: [user.id] }),
}));

export const reviewLogsRelations = relations(reviewLogs, ({ one }) => ({
  user: one(user, { fields: [reviewLogs.userId], references: [user.id] }),
  flashcard: one(flashcards, { fields: [reviewLogs.flashcardId], references: [flashcards.id] }),
}));

export const userXPRelations = relations(userXP, ({ one }) => ({
  user: one(user, { fields: [userXP.userId], references: [user.id] }),
}));

export const userAchievementsRelations = relations(userAchievements, ({ one }) => ({
  user: one(user, { fields: [userAchievements.userId], references: [user.id] }),
}));

export const dailyChallengesRelations = relations(dailyChallenges, ({ one }) => ({
  user: one(user, { fields: [dailyChallenges.userId], references: [user.id] }),
}));
